### ISSUE TITLE
Apply Liquidbase

### ISSUE THREAD

**Issue by plozanol** [github-stats-22/github-stats#8]
As a developer, I want to apply a database changes version control

Context:
- once the base Entity model is settled, a DB change version control will be useful to track all changes, and rollback if needed
- in the first stage, hibernate will be responsible of autogenerating the database, tables, and relations and updating them on every run of the application.

Acceptance:
- liquidbase library will be used in the project
- all DB base creation will be defined by liquidbase in a YAML or XML file
- just to double check, hibernate will check that all annotations in the application match with the database managed by liquidbase

**Comment by mikededo** [comment]
Like the feature, did not know it existed. We should probably split the ticket, wdyt?

**Comment by plozanol** [comment]
I already implemented this at #36 , so we can close this issue
