### ISSUE TITLE
feat: `TeamOptionController`

### ISSUE THREAD

**Issue by sdomingobasora** [github-stats-22/github-stats#96]
### Description

After finishing the `UserOptionController` (see issue #70), we will need to implement a controller for the Team shell option.

The structure of the `TeamOptionController` might end up being quite similar to the `UserOptionController`, and that is why contributors for this task should keep a close eye to changes on `UserOptionController` as that class is being heavily worked on.

Contributors for this task could operate on the branch `feat/team_option_controller` which is only merged once the full controller is finished. Separate small PRs could depart from that separate branch. That might keep things consistent with how `UserOptionController` was set up.

**We might want to wait until all use cases are finished before branching out from main and starting this task.**

### To do

- Create branch `feat/team_option_controller`
- Create class `TeamOptionController`

**Comment by mikededo** [comment]
Since we have remove the feature branch for the `UserOptionController`, how do you feel about **not having a feature branch for the `TeamOptionController`**?

Thoughts? @manerow @plozanol @sdomingobasora @cjp4

**Comment by mikededo** [comment]
We will implement this in the same `GitHubController` as we will depend on the `EntityType`.
